# Generated by Django 3.0.6 on 2020-05-25 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.AddField(
            model_name='product',
            name='out_stock',
            field=models.BooleanField(default=False),
        ),
    ]
