# Generated by Django 3.0.6 on 2020-05-26 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20200526_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(blank=True, choices=[('Normal', 'Normal'), ('New', 'New'), ('Hot', 'Hot'), ('Sale', 'Sale')], default='Normal', max_length=50, null=True),
        ),
    ]
