# Generated by Django 3.0.6 on 2020-06-03 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20200602_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='ads')),
                ('link_to', models.URLField(default='/')),
            ],
            options={
                'verbose_name_plural': 'Ads',
            },
        ),
    ]
