# Generated by Django 3.0.6 on 2020-06-08 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_ads'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='remark',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='ads',
            name='link_to',
            field=models.URLField(default=''),
        ),
    ]
